feat: improve local setup with macOS virtualization guidance and UX enhancements (platform-mesh/helm-charts#757)
* feat: add macOS virtualization framework check and guidance

Signed-off-by: Bastian Echterhölter <bastian.echterhoelter@sap.com>
On-behalf-of: @SAP <bastian.echterhoelter@sap.com>

* feat: Various smaller improvements

Signed-off-by: Bastian Echterhölter <bastian.echterhoelter@sap.com>
On-behalf-of: @SAP <bastian.echterhoelter@sap.com>

* feat: remove macOS virtualization framework check and update documentation

Signed-off-by: Bastian Echterhölter <bastian.echterhoelter@sap.com>
On-behalf-of: @SAP <bastian.echterhoelter@sap.com>

---------

Signed-off-by: Bastian Echterhölter <bastian.echterhoelter@sap.com>

Includes the changes of 2 automated commit(s) squashed into this one
during the monorepo import.

diff --git a/hack/import/parked/helm-charts-Taskfile.yaml b/hack/import/parked/helm-charts-Taskfile.yaml
--- a/hack/import/parked/helm-charts-Taskfile.yaml
+++ b/hack/import/parked/helm-charts-Taskfile.yaml
@@ -493,8 +493,10 @@ tasks:
       FLAGS: '{{.FLAGS | default ""}}'
     cmds:
       - |
-        read -r -p "Are you sure you want to delete the cluster? [y/N] " response && if [ "$response" != "y" ]; then echo "Aborted."; exit 1; fi
-        kind delete cluster --name platform-mesh
+        if kind get clusters 2>/dev/null | grep -q "^platform-mesh$"; then
+          read -r -p "Are you sure you want to delete the cluster? [y/N] " response && if [ "$response" != "y" ]; then echo "Aborted."; exit 1; fi
+          kind delete cluster --name platform-mesh
+        fi
         ./local-setup/scripts/start.sh {{.FLAGS}}
 
   local-setup:iterate:
